"""
backtest.py
-----------
Layer 4: BACKTEST + EVALUATION

For each signal day (heavy_buying / heavy_selling), measures what actually
happened to the price over several forward holding periods, and compares
that against the stock's overall baseline forward-return distribution using
a two-sample t-test -- so the report can defend "this zone shows heavy
buying" statistically, not just visually.
"""

import pandas as pd
from scipy import stats


def forward_returns(price: pd.Series, holding_periods=(21, 63, 126, 252)) -> pd.DataFrame:
    """
    holding_periods are in TRADING days by default:
    21 ~ 1 month, 63 ~ 3 months, 126 ~ 6 months, 252 ~ 1 year.
    Uses price.shift(-h) deliberately -- this IS forward-looking by design,
    because we're measuring what happens AFTER a signal, which is exactly
    what a backtest needs (not a bug, unlike the lookahead risk in PE ranking).
    """
    fwd = pd.DataFrame(index=price.index)
    for h in holding_periods:
        fwd[f"fwd_ret_{h}d"] = price.shift(-h) / price - 1
    return fwd


def evaluate_signal(signal_mask: pd.Series, fwd_returns: pd.DataFrame, min_signal_obs: int = 5) -> pd.DataFrame:
    """
    Returns a tidy DataFrame, one row per holding period, with:
    n_signals, avg_signal_return, avg_baseline_return, win_rate, t_stat, p_value.

    p_value < 0.05 is a common convention for "statistically distinguishable
    from baseline" -- but with multiple holding periods and multiple stocks
    tested, correcting for multiple comparisons (e.g. Bonferroni) is worth
    doing before making strong claims in the report, rather than treating
    each p-value in isolation.
    """
    rows = []
    for col in fwd_returns.columns:
        signal_rets = fwd_returns.loc[signal_mask.reindex(fwd_returns.index, fill_value=False), col].dropna()
        baseline_rets = fwd_returns[col].dropna()

        if len(signal_rets) < min_signal_obs:
            rows.append({
                "holding_period": col,
                "n_signals": len(signal_rets),
                "avg_signal_return": signal_rets.mean() if len(signal_rets) else None,
                "avg_baseline_return": baseline_rets.mean(),
                "win_rate": (signal_rets > 0).mean() if len(signal_rets) else None,
                "t_stat": None,
                "p_value": None,
                "note": "too few signal observations for a reliable t-test",
            })
            continue

        t_stat, p_val = stats.ttest_ind(signal_rets, baseline_rets, equal_var=False)
        rows.append({
            "holding_period": col,
            "n_signals": len(signal_rets),
            "avg_signal_return": signal_rets.mean(),
            "avg_baseline_return": baseline_rets.mean(),
            "win_rate": (signal_rets > 0).mean(),
            "t_stat": t_stat,
            "p_value": p_val,
            "note": "",
        })
    return pd.DataFrame(rows)


def run_backtest(df: pd.DataFrame, holding_periods=(21, 63, 126, 252)) -> dict:
    """
    df must contain: 'price', 'heavy_buying', 'heavy_selling' columns.
    Returns {'buy_signal_eval': DataFrame, 'sell_signal_eval': DataFrame}.
    """
    fwd = forward_returns(df["price"], holding_periods)
    return {
        "buy_signal_eval": evaluate_signal(df["heavy_buying"], fwd),
        "sell_signal_eval": evaluate_signal(df["heavy_selling"], fwd),
    }

def run_ablation_backtest(df: pd.DataFrame, holding_periods=(21, 63, 126, 252)) -> dict:
    """
    Runs the forward returns evaluation strictly on the isolated ablation columns
    generated by generate_ablation_signals.
    """
    fwd = forward_returns(df["price"], holding_periods)
    
    return {
        "buy_pe_only": evaluate_signal(df.get("buy_pe_only", pd.Series(False, index=df.index)), fwd),
        "buy_technical_only": evaluate_signal(df.get("buy_technical_only", pd.Series(False, index=df.index)), fwd),
        "buy_combined": evaluate_signal(df.get("buy_combined", pd.Series(False, index=df.index)), fwd),
        
        "sell_pe_only": evaluate_signal(df.get("sell_pe_only", pd.Series(False, index=df.index)), fwd),
        "sell_technical_only": evaluate_signal(df.get("sell_technical_only", pd.Series(False, index=df.index)), fwd),
        "sell_combined": evaluate_signal(df.get("sell_combined", pd.Series(False, index=df.index)), fwd),
    }
